In [33]:
import numpy as np
import tensorflow as tf

In [34]:

inputvals  = [[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1],
              [1, 1, 0], [1, 1, 1]]
targetvals = [[0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0],
              [1, 1, 1], [0, 0, 0]]

testinputs  = [[0, 1, 0], [0, 1, 1], [0, 0, 1], [1, 1, 1], [1, 0, 1],
               [1, 0, 0], [0, 0, 0], [1, 1, 0]]
testtargets = [[0, 1, 1], [1, 0, 0], [0, 1, 0], [0, 0, 0], [1, 1, 0],
               [1, 0, 1], [0, 0, 1], [1, 1, 1]]

num_inputs = 3
num_hiddens = 5
num_outputs = 3

dataset = tf.placeholder(tf.float32, shape=[None, num_inputs])
labels = tf.placeholder(tf.float32, shape=[None, num_outputs])


In [35]:
w_fc1 = tf.Variable(tf.truncated_normal([num_inputs, num_hiddens], 0.0, 1.0))
b_fc1 = tf.Variable(tf.truncated_normal([num_hiddens], 0.0, 1.0))
h_fc1 = tf.nn.relu(tf.matmul(dataset, w_fc1) + b_fc1)

w_fc2 = tf.Variable(tf.truncated_normal([num_hiddens, num_outputs], 0.0, 1.0))
b_fc2 = tf.Variable(tf.truncated_normal([num_outputs], 0.0, 1.0))

y = tf.matmul(h_fc1, w_fc2) + b_fc2


In [36]:
cross_entropy = tf.reduce_mean(
      tf.nn.sigmoid_cross_entropy_with_logits(logits=y, targets=labels))
train_step = tf.train.RMSPropOptimizer(0.25, momentum=0.5).minimize(cross_entropy)
train_adaelta = tf.train.AdadeltaOptimizer(0.25).minimize(cross_entropy)
train_adam = tf.train.AdamOptimizer(0.25).minimize(cross_entropy)
prediect = tf.sigmoid(y)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(10000):
        loss = cross_entropy.eval(feed_dict={dataset: inputvals, labels:targetvals})
        if i % 1000 == 0:
            print i, loss
        if loss < 1e-5:
            print i, loss
            break
        sess.run([train_adam], feed_dict={dataset: inputvals, labels:targetvals}) 
    print sess.run(prediect, feed_dict={dataset: testinputs})    
                                             

0 0.669408
1000 0.571268
2000 0.402815
3000 0.25056
4000 0.17033
5000 0.123866
6000 0.0859194
7000 0.0573583
8000 0.041371
9000 0.0308091
[[  2.07872596e-02   9.70207632e-01   9.93233383e-01]
 [  9.18783247e-01   3.43585569e-08   3.15695470e-05]
 [  5.73312268e-02   9.95200872e-01   4.34351296e-06]
 [  9.72008109e-02   1.56605691e-02   4.69514262e-03]
 [  9.39312160e-01   9.92303669e-01   4.13885107e-03]
 [  9.99991894e-01   7.02076708e-04   9.99530554e-01]
 [  6.17432371e-02   4.64393832e-02   9.84678745e-01]
 [  9.86704707e-01   9.85307217e-01   9.99857545e-01]]
